### PR TITLE
feat: add simple and convinient install.sh

### PR DESCRIPTION
**Pull request by doodlesbykumbi**
**NOTE** this PR doesn't require/entail a release

## How to verify this PR

+ vet the changes to README.md
+ run the installation script (instead of pointing at `master`, point to this branch `install-sh`) and confirm that `summon-conjur` is successfully installed at `/usr/local/lib/summon`

You can also run this in an environment that has machine identity and try to retrieve a secret while you're at it :)

### CODE REVIEW

**Review by mizziness — COMMENTED** [review]
In my environment, I needed to run the command as root because running it with just `sudo` wasn't enough for my VM.  Other than that, it works fine!

If that is okay with you, then I can approve.  Otherwise, we might want to add a note to the README saying as such.

image

**Comment by doodlesbykumbi** [comment]
@mizziness i've removed `sudo`. it seems there's no particular need for that. please run through it again from scratch if possible - ideally, as a non-root user. if it works we're good to go

**Comment by mizziness** [comment]
@doodlesbykumbi  No luck:

```
vagrant@vagrant:/dev_code$ curl -sSL https://raw.githubusercontent.com/cyberark/summon-conjur/install-sh/install.sh | bash
Downloading https://github.com/cyberark/summon-conjur/releases/download/v0.4.0/summon-conjur-linux-amd64.tar.gz
wget: Cannot read /home/vagrant/.netrc (Permission denied).
Installing summon vv0.4.0 into /usr/local/lib/summon
mkdir: cannot create directory ‘/usr/local/lib/summon’: Permission denied
```

**Review by mizziness — APPROVED** [review]
The README is correct and local tests prove functional as intended!  There is one error with my local .netrc file permissions, but the command and script still work - it is a non-blocking, and potentially edge-case, error.

**Pull request merged**
